### ISSUE TITLE
1.0.3版本 掉落物太多清理时候导致服务器崩溃

### ISSUE THREAD

**Issue by mcratt** [Nova-Committee/Atom-Sweep#1]
应该是下标越界吗。

Exception caught during firing event: Index 1919 out of bounds for length 1025
        Index: 6
        Listeners:
                0: HIGH
                1: ASM: class dev.architectury.event.forge.EventHandlerImplCommon event(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
                2: NORMAL
                3: ASM: class dev.ftb.mods.ftbessentials.FTBEEventHandler serverTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
                4: ASM: net.minecraftforge.common.ForgeInternalHandler@e8e46bb onServerTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
                5: ASM: class gg.moonflower.pollen.core.forge.PollenCommonForgeEvents onEvent(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
                6: ASM: class nova.committee.atom.sweep.init.handler.SweepHandler onServerTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
                7: ASM: class com.simibubi.create.events.CommonEvents onServerTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
java.lang.ArrayIndexOutOfBoundsException: Index 1919 out of bounds for length 1025
        at MC-BOOTSTRAP/it.unimi.dsi.fastutil@8.5.6/it.unimi.dsi.fastutil.ints.Int2ObjectLinkedOpenHashMap$MapIterator.forEachRemaining(Int2ObjectLinkedOpenHashMap.java:1255)
        at MC-BOOTSTRAP/it.unimi.dsi.fastutil@8.5.6/it.unimi.dsi.fastutil.ints.Int2ObjectLinkedOpenHashMap$ValueIterator.forEachRemaining(Int2ObjectLinkedOpenHashMap.java:1720)
        at MC-BOOTSTRAP/it.unimi.dsi.fastutil@8.5.6/it.unimi.dsi.fastutil.objects.ObjectSpliterators$SpliteratorFromIterator.forEachRemaining(ObjectSpliterators.java:1194)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at TRANSFORMER/atomsweep@1.18.2-0.1.3/nova.committee.atom.sweep.core.Sweeper.cleanupEntity(Sweeper.java:145)
        at TRANSFORMER/atomsweep@1.18.2-0.1.3/nova.committee.atom.sweep.core.Sweeper.cleanupItemEntity(Sweeper.java:120)
        at TRANSFORMER/atomsweep@1.18.2-0.1.3/nova.committee.atom.sweep.core.Sweeper.sweep(Sweeper.java:100)
        at TRANSFORMER/atomsweep@1.18.2-0.1.3/nova.committee.atom.sweep.init.handler.SweepHandler.lambda$onServerTick$0(SweepHandler.java:34)
        at java.base/java.util.Optional.ifPresent(Optional.java:178)
        at TRANSFORMER/atomsweep@1.18.2-0.1.3/nova.committee.atom.sweep.init.handler.SweepHandler.onServerTick(SweepHandler.java:31)
        at net.minecraftforge.eventbus.ASMEventHandler_422_SweepHandler_onServerTick_ServerTickEvent.invoke(.dynamic)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
        at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
        at TRANSFORMER/forge@40.1.86/net.minecraftforge.event.ForgeEventFactory.onPostServerTick(ForgeEventFactory.java:953)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:879)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685)
        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261)
        at java.base/java.lang.Thread.run(Thread.java:833)

[17:28:11] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
java.lang.ArrayIndexOutOfBoundsException: Index 1919 out of bounds for length 1025
        at it.unimi.dsi.fastutil.ints.Int2ObjectLinkedOpenHashMap$MapIterator.forEachRemaining(Int2ObjectLinkedOpenHashMap.java:1255) ~[fastutil-8.5.6.jar%2330!/:?] {}
        at it.unimi.dsi.fastutil.ints.Int2ObjectLinkedOpenHashMap$ValueIterator.forEachRemaining(Int2ObjectLinkedOpenHashMap.java:1720) ~[fastutil-8.5.6.jar%2330!/:?] {}
        at it.unimi.dsi.fastutil.objects.ObjectSpliterators$SpliteratorFromIterator.forEachRemaining(ObjectSpliterators.java:1194) ~[fastutil-8.5.6.jar%2330!/:?] {}
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?] {}
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?] {}
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?] {}
        at nova.committee.atom.sweep.core.Sweeper.cleanupEntity(Sweeper.java:145) ~[服务端-基石-清理-Atom-Sweep-forge-1.18.2-0.1.3_.jar%2374!/:1.18.2-0.1.3] {re:classloading,pl:rei_plugin_compatibilities:B}
        at nova.committee.atom.sweep.core.Sweeper.cleanupItemEntity(Sweeper.java:120) ~[服务端-基石-清理-Atom-Sweep-forge-1.18.2-0.1.3_.jar%2374!/:1.18.2-0.1.3] {re:classloading,pl:rei_plugin_compatibilities:B}
        at nova.committee.atom.sweep.core.Sweeper.sweep(Sweeper.java:100) ~[服务端-基石-清理-Atom-Sweep-forge-1.18.2-0.1.3_.jar%2374!/:1.18.2-0.1.3] {re:classloading,pl:rei_plugin_compatibilities:B}
        at nova.committee.atom.sweep.init.handler.SweepHandler.lambda$onServerTick$0(SweepHandler.java:34) ~[服务端-基石-清理-Atom-Sweep-forge-1.18.2-0.1.3_.jar%2374!/:1.18.2-0.1.3] {re:classloading,pl:rei_plugin_compatibilities:B}
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin}
        at nova.committee.atom.sweep.init.handler.SweepHandler.onServerTick(SweepHandler.java:31) ~[服务端-基石-清理-Atom-Sweep-forge-1.18.2-0.1.3_.jar%2374!/:1.18.2-0.1.3] {re:classloading,pl:rei_plugin_compatibilities:B}
        at net.minecraftforge.eventbus.ASMEventHandler_422_SweepHandler_onServerTick_ServerTickEvent.invoke(.dynamic) ~[?:?] {}
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
        at net.minecraftforge.event.ForgeEventFactory.onPostServerTick(ForgeEventFactory.java:953) ~[forge-1.18.2-40.1.86-universal.jar%23129!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:rei_plugin_compatibilities:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:879) ~[server-1.18.2-20220404.173914-srg.jar%23124!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[server-1.18.2-20220404.173914-srg.jar%23124!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[server-1.18.2-20220404.173914-srg.jar%23124!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:balm.mixins.json:MinecraftServer

**Comment by cnlimiter** [comment]
0.1.4已修复
