### ISSUE TITLE
[Bug/漏洞] 进入地图时崩溃

### ISSUE THREAD

**Issue by iamsoNewBee** [Nova-Committee/Atom-Sweep#13]
### Checks / 检查

- [X] I confirm that I have [searched for existing issues / pull requests](https://github.com/cnlimiter/Atom-Sweep/issues?q=) before reporting to avoid duplicate reporting./我确认在报告之前我已经搜索了[现有的问题或者拉取请求](https://github.com/cnlimiter/McBot/issues?q=)，以避免重复报告。
- [X] I confirm that I followed the Docs and read the [Changelog](https://github.com/cnlimiter/Atom-Sweep/releases/latest), but this problem still exists./我确认我按照文档配置并阅读了[Changelog](https://github.com/cnlimiter/McBot/releases/latest)，但这个问题仍然存在。
- [X] I confirm that I noted that if I don't follow the instructions, the issue may be closed directly./我确认我已经检查，如果我不按照说明进行操作，该问题可能会被直接关闭。

### Java Version / Java版本

java8 401

### Minecraft Version / Minecraft版本

1.16.5

### McBot Version / Atom-Sweep版本

最新版

### Description / 描述

[crash-2024-04-08_16.26.12-server.txt](https://github.com/Nova-Committee/Atom-Sweep/files/14905332/crash-2024-04-08_16.26.12-server.txt)

### To Reproduce / 重现

 1

### Log / 日志

 1

**Comment by cnlimiter** [comment]
@iamsoNewBee 
java.lang.NullPointerException: Exception in server tick loop
	at cam72cam.mod.sound.Audio.lambda$registerClientCallbacks$2(Audio.java:46) ~[_universalmodcore_:1.1.3] {re:classloading}
	at cam72cam.mod.event.CommonEvents$EventBusForge.lambda$onWorldLoad$0(CommonEvents.java:66) ~[universalmodcore:1.1.3] {re:classloading}
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_281] {}
	at cam72cam.mod.event.Event.execute(Event.java:24) ~[universalmodcore:1.1.3] {re:classloading}
	at cam72cam.mod.event.CommonEvents$EventBusForge.onWorldLoad(CommonEvents.java:66) ~[universalmodcore:1.1.3] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_2367_EventBusForge_onWorldLoad_Load.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraft.server.MinecraftServer.func_240787_a_(MinecraftServer.java:379) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-

不是基石清理的问题

**Comment by cnlimiter** [comment]
universalmodcore的问题

**Comment by iamsoNewBee** [comment]
有办法可以一起用吗？删除atom后无崩溃问题
